# Generated by Django 4.1 on 2022-08-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0005_suitecase'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('env', models.CharField(default='', max_length=50, verbose_name='环境')),
                ('ip', models.CharField(default='', max_length=50, verbose_name='ip')),
                ('port', models.CharField(default='', max_length=100, verbose_name='端口')),
                ('remark', models.CharField(max_length=100, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '接口地址配置表',
                'verbose_name_plural': '接口地址配置表',
            },
        ),
    ]
